name: Run tests

on:
  push:

  workflow_dispatch:

permissions:
  contents: write
  actions: write
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Golang
      uses: actions/setup-go@v5 
      with:
        go-version: 'stable'

    - name: Run tests
      run: go test -v -coverprofile=coverage.out ./...

    - name: Calculate coverage
      id: coverage
      run: |
        COVERAGE=$(go tool cover -func=coverage.out | grep total: | awk '{print $3}' | sed 's/%//')
        echo "Coverage percentage: $COVERAGE"
        echo "::set-output name=coverage::${COVERAGE}"
        
    - name: Generate coverage badge (ImgShields)
      run: |
          curl -o coverage-badge.svg "https://img.shields.io/badge/coverage-${{ steps.coverage.outputs.coverage }}%25-brightgreen"

    - name: Commit the badge (if it has changed)
      run: |
        if [[ $(git status --porcelain) ]]; then
          git config --global user.name '50-Course'
          git config --global user.email '50-Course@users.noreply.github.com'
          git add coverage-badge.svg
          git commit -m 'chore: update coverage badge'
          git push
        fi
